#!/bin/bash

echo "🚨 URGENT FIX: OAuth & Database Issues"
echo "====================================="
echo ""

echo "📊 CURRENT STATUS:"
echo "❌ OAuth: Error 401 - invalid_client"
echo "❌ Database: MongoServerSelectionError - connection closed"
echo "❌ API: 500 errors on /api/blogs"
echo ""

echo "🔧 IMMEDIATE FIXES REQUIRED:"
echo ""

echo "1️⃣ GOOGLE OAUTH FIX (CRITICAL):"
echo "   • Problem: Callback URL not configured in Google Cloud Console"
echo "   • Go to: https://console.cloud.google.com/"
echo "   • Navigate: APIs & Services → Credentials"
echo "   • Edit your OAuth 2.0 Client ID"
echo "   • Add Authorized redirect URI:"
echo "     https://next-js-full-stack-blog.vercel.app/api/auth/callback/google"
echo ""

echo "2️⃣ DATABASE CONNECTION FIX (CRITICAL):"
echo "   • Current Error: MongoServerSelectionError - connection closed"
echo "   • Go to Vercel Dashboard → Settings → Environment Variables"
echo "   • Update MONGODB_URI to:"
echo ""
echo "MONGODB_URI:"
echo "mongodb+srv://ys68687:yllimali123@clusternext.zlp4afn.mongodb.net/myapp?retryWrites=true&w=majority&ssl=false&appName=NextJSFullStackBlog"
echo ""

echo "3️⃣ VERCEL DEPLOYMENT:"
echo "   • After updating environment variables"
echo "   • Go to Deployments tab"
echo "   • Click 'Redeploy' on latest deployment"
echo ""

echo "🧪 TEST COMMANDS (after fixes):"
echo ""
echo "# Test OAuth providers:"
echo "curl https://next-js-full-stack-blog.vercel.app/api/auth/providers"
echo ""
echo "# Test database connection:"
echo "curl https://next-js-full-stack-blog.vercel.app/api/test-connection"
echo ""
echo "# Test blog API:"
echo "curl https://next-js-full-stack-blog.vercel.app/api/blogs"
echo ""

echo "⚠️ PRIORITY ORDER:"
echo "1. Fix Google OAuth callback URL (highest priority)"
echo "2. Update MONGODB_URI with ssl=false"
echo "3. Redeploy on Vercel"
echo "4. Test all endpoints"
echo ""

echo "✅ EXPECTED RESULTS:"
echo "• Google sign-in works without 401 error"
echo "• Database operations successful"
echo "• Blog loading works"
echo "• User registration works"
