#!/bin/bash

echo "🔧 DEPLOYING VERCEL SSL/TLS FIX"
echo "=============================="
echo ""

echo "📋 ENVIRONMENT VARIABLES TO UPDATE:"
echo ""
echo "1. MONGODB_URI:"
echo "   mongodb+srv://ys68687:yllimali123@clusternext.zlp4afn.mongodb.net/myapp?retryWrites=true&w=majority&appName=NextJSFullStackBlog&ssl=true&tlsAllowInvalidCertificates=false&serverSelectionTimeoutMS=5000"
echo ""
echo "2. NEXTAUTH_SECRET:"
echo "   [YOUR_NEXTAUTH_SECRET_HERE]"
echo ""
echo "3. NEXTAUTH_URL:"
echo "   https://next-js-full-stack-blog.vercel.app"
echo ""

echo "🚀 DEPLOYMENT STEPS:"
echo "1. Update environment variables in Vercel dashboard"
echo "2. Redeploy your application"
echo "3. Test the endpoints below"
echo ""

echo "🧪 TEST ENDPOINTS AFTER DEPLOYMENT:"
echo "=================================="
echo ""
echo "1. Database Connection Test:"
echo "   https://next-js-full-stack-blog.vercel.app/api/test-connection"
echo ""
echo "2. Full Deployment Test:"
echo "   https://next-js-full-stack-blog.vercel.app/api/vercel-test"
echo ""
echo "3. Blog Pages:"
echo "   https://next-js-full-stack-blog.vercel.app/blogs"
echo ""
echo "4. User Registration:"
echo "   https://next-js-full-stack-blog.vercel.app/sign-up"
echo ""

echo "✅ EXPECTED RESULTS:"
echo "==================="
echo "- No more SSL/TLS errors"
echo "- Database connection successful"
echo "- User registration/login works"
echo "- Blogs display correctly"
echo ""

echo "🔗 QUICK LINKS:"
echo "==============="
echo "Vercel Dashboard: https://vercel.com/dashboard"
echo "Your Project: https://next-js-full-stack-blog.vercel.app"
echo ""

echo "⚡ The code has been updated with SSL fixes!"
echo "   Now update your Vercel environment variables and redeploy."
