#!/bin/bash

echo "🔍 VERCEL DEPLOYMENT TROUBLESHOOTING"
echo "===================================="
echo ""
echo "Let's diagnose what's still not working..."
echo ""

# Check if we can reach the site
echo "1. 🌐 Testing if your site is accessible..."
curl -I https://next-js-full-stack-blog.vercel.app 2>/dev/null | head -1 || echo "❌ Site not accessible"

echo ""
echo "2. 🔍 Common issues to check:"
echo ""
echo "📋 ENVIRONMENT VARIABLES CHECKLIST:"
echo "   □ NEXTAUTH_SECRET - Added to Vercel?"
echo "   □ NEXTAUTH_URL - Set to https://next-js-full-stack-blog.vercel.app?"
echo "   □ MONGODB_URI - Added to Vercel?"
echo "   □ All variables set for Production, Preview, AND Development?"
echo ""
echo "📋 VERCEL SETTINGS CHECKLIST:"
echo "   □ Root Directory set to 'blog'?"
echo "   □ Did you redeploy after adding environment variables?"
echo "   □ Build completed successfully?"
echo ""
echo "📋 SPECIFIC CHECKS NEEDED:"
echo "   □ Check Vercel build logs for errors"
echo "   □ Check runtime logs for errors"
echo "   □ Test specific endpoints"
echo ""
echo "🚨 CRITICAL QUESTIONS:"
echo "   1. Did you add the environment variables to VERCEL dashboard (not just local .env)?"
echo "   2. Did you redeploy AFTER adding the environment variables?"
echo "   3. What specific error are you seeing now?"
echo ""
echo "🔧 NEXT STEPS:"
echo "   1. Go to https://vercel.com/dashboard"
echo "   2. Find your project"
echo "   3. Check Settings → Environment Variables"
echo "   4. Verify all 5 variables are there"
echo "   5. Check latest deployment logs"
echo ""
echo "📞 PLEASE SHARE:"
echo "   - What error message you're seeing now"
echo "   - Screenshot of your Vercel environment variables"
echo "   - Any error logs from Vercel dashboard"
